disabled_rules: # rule identifiers to exclude from running
  - nesting
  - type_name
  - force_cast
  - line_length
  - large_tuple
  - identifier_name
  - type_body_length
  - function_body_length
  - orphaned_doc_comment
  - cyclomatic_complexity
  - void_function_in_ternary
  - non_optional_string_data_conversion
  
file_length:
  warning: 400
  error: 500
