name: Build
on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      
      - name: Install the Apple certificate and provisioning profile
        run: |
          chmod +x install_dist_certs.sh && ./install_dist_certs.sh
          chmod +x install_dist_profile.sh && ./install_dist_profile.sh

      - name: Install pods
        run: |
          arch -x86_64 pod install --repo-update

      - name: Run lint
        run: |
          Pods/SwiftLint/swiftlint Splito

      - name: Archive project
        run: |
          ARCHIVE_PATH="$HOME/Library/Developer/Xcode/Archives/Splito/${CI_COMMIT_SHA}/${CI_JOB_ID}.xcarchive"
          xcodebuild -workspace Splito.xcworkspace -scheme "Splito" clean archive -sdk iphoneos -archivePath $ARCHIVE_PATH | xcpretty --color
          rm -rf $ARCHIVE_PATH
