name: Build

on: push

jobs:
  build:
    runs-on: macos-13
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          
      - name: Set Xcode Version
        run: |
          sudo xcode-select -switch /Applications/Xcode_15.2.app
          
      - name: Display Xcode Version
        run: /usr/bin/xcodebuild -version
          
      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: |
            Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
            
      - name: Install CocoaPods
        run: |
          if [ -f "Podfile.lock" ] && [ -f "${{ runner.workspace }}/Podfile.lock" ] && cmp -s Podfile.lock "${{ runner.workspace }}/Podfile.lock"; then
            echo "Podfile.lock unchanged. Skipping pod installs."
          else
            gem install cocoapods
            pod install --repo-update
          fi

      - name: Run SwiftLint if Needed
        run: |
          if git diff --name-only ${{ github.sha }} | grep -q '\.swift$'; then
            Pods/SwiftLint/swiftlint Splito
          else
            echo "No Swift files changed. Skipping SwiftLint."
          fi
          
      - name: Build Project
        run: |
          xcodebuild clean build -workspace Splito.xcworkspace -scheme "Splito" | xcpretty --color
